# Generated by Django 3.2 on 2021-05-20 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RES', '0003_treemenuz'),
    ]

    operations = [
        migrations.AddField(
            model_name='treemenuv',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RES.devicemercuryv'),
        ),
    ]
