# Generated by Django 3.2 on 2021-04-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.DecimalField(decimal_places=65535, max_digits=65535, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('password', models.DecimalField(decimal_places=65535, max_digits=65535)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
